/**
 * This file contains constants used across the documentation pages.
 * It includes table of contents items, code snippets for examples, and CLI commands.
 * Keeping these in a separate file helps maintain consistency and makes it easier to update content in one place.
 */
export const tocItems = [
  { id: 'installation', title: 'Installation', level: 2 },
  { id: 'usage', title: 'Usage', level: 2 },
  { id: 'cli-commands', title: 'CLI Commands', level: 2 },
  { id: 'theming', title: 'Theming', level: 2 },
  { id: 'theme-cli', title: 'Theme CLI', level: 3 },
  { id: 'customizing', title: 'Customizing', level: 3 },
  { id: 'runtime-theming', title: 'Runtime Switching', level: 3 },
  { id: 'how-it-works', title: 'How It Works', level: 2 },
];

export const themeCommands = `# Initialize or replace your theme
npx pdfx-cli theme init

# Switch to a different preset
npx pdfx-cli theme switch modern

# Validate your theme file
npx pdfx-cli theme validate`;

export const themeCustomization = `// src/lib/pdfx-theme.ts — edit any token to restyle every component at once.
// The PdfxTheme type is defined inline in this file — no extra imports needed.

export const theme: PdfxTheme = {
  name: 'my-brand',
  colors: {
    primary: '#2563eb',        // your brand color
    accent: '#7c3aed',         // links and highlights
    foreground: '#1a1a1a',     // body text
    background: '#ffffff',
    muted: '#f4f4f5',
    mutedForeground: '#71717a',
    primaryForeground: '#ffffff',
    border: '#e4e4e7',
    destructive: '#dc2626',
    success: '#16a34a',
    warning: '#d97706',
    info: '#0ea5e9',
  },
  typography: {
    heading: {
      fontFamily: 'Helvetica-Bold',  // swap any registered @react-pdf font
      fontWeight: 700,
      lineHeight: 1.2,
      fontSize: { h1: 36, h2: 28, h3: 22, h4: 18, h5: 15, h6: 12 },
    },
    body: {
      fontFamily: 'Helvetica',
      fontSize: 11,
      lineHeight: 1.5,
    },
  },
  // ... primitives, spacing, page (all required — copy from the scaffolded file)
};`;

export const usageExample = `import { Document, Page } from '@react-pdf/renderer';
import { Heading } from '@/components/pdfx/heading/pdfx-heading';
import { Text } from '@/components/pdfx/text/pdfx-text';

export function MyDocument() {
  return (
    <Document>
      <Page size="A4" style={{ padding: 30 }}>
        <Heading level={1}>Hello World</Heading>
        <Text>This is a paragraph of body text.</Text>
      </Page>
    </Document>
  );
}`;

export const cliCommands = `# Initialize PDFx in your project (includes theme setup)
npx pdfx-cli init

# Add components
npx pdfx-cli add heading text

# List available components
npx pdfx-cli list

# Compare local vs registry
npx pdfx-cli diff heading`;

export const manualStep1Deps = 'npm install @react-pdf/renderer';

export const manualStep2Pdfxjson = `{
  "$schema": "https://pdfx.akashpise.dev/schema.json",
  "registry": "https://pdfx.akashpise.dev/r",
  "componentDir": "src/components/pdfx",
  "theme": "./src/lib/pdfx-theme.ts"
}`;

// NOTE: componentDir "src/components/pdfx" is intentional — PDF components are
// kept in their own subdirectory to avoid conflicts with regular UI components.

export const manualStep3Theme = `// This file was generated by pdfx init. You own it — customize freely.
// Docs: https://pdfx.akashpise.dev/installation#theming
//
// All PDF components read their styling tokens from this file.
// Edit values below to change the look of every component at once.

// PdfxTheme type is inlined here — no @pdfx/shared dependency needed.
interface PdfxTheme {
  name: string;
  primitives: {
    typography: Record<string, number>;
    spacing: Record<string | number, number>;
    fontWeights: { regular: number; medium: number; semibold: number; bold: number };
    lineHeights: { tight: number; normal: number; relaxed: number };
    borderRadius: { none: number; sm: number; md: number; lg: number; full: number };
    letterSpacing: { tight: number; normal: number; wide: number; wider: number };
  };
  colors: {
    foreground: string; background: string; muted: string; mutedForeground: string;
    primary: string; primaryForeground: string; border: string; accent: string;
    destructive: string; success: string; warning: string; info: string;
  };
  typography: {
    body: { fontFamily: string; fontSize: number; lineHeight: number };
    heading: {
      fontFamily: string; fontWeight: number; lineHeight: number;
      fontSize: { h1: number; h2: number; h3: number; h4: number; h5: number; h6: number };
    };
  };
  spacing: {
    page: { marginTop: number; marginRight: number; marginBottom: number; marginLeft: number };
    sectionGap: number; paragraphGap: number; componentGap: number;
  };
  page: { size: 'A4' | 'LETTER' | 'LEGAL'; orientation: 'portrait' | 'landscape' };
}

export const theme: PdfxTheme = {
  name: 'professional',
  primitives: {
    typography: { xs: 10, sm: 12, base: 15, lg: 18, xl: 22, '2xl': 28, '3xl': 36 },
    spacing: { 0: 0, 0.5: 2, 1: 4, 2: 8, 3: 12, 4: 16, 5: 20, 6: 24, 8: 32, 10: 40, 12: 48, 16: 64 },
    fontWeights: { regular: 400, medium: 500, semibold: 600, bold: 700 },
    lineHeights: { tight: 1.2, normal: 1.4, relaxed: 1.6 },
    borderRadius: { none: 0, sm: 2, md: 4, lg: 8, full: 9999 },
    letterSpacing: { tight: -0.025, normal: 0, wide: 0.025, wider: 0.05 },
  },
  colors: {
    foreground: '#18181b',
    background: '#ffffff',
    muted: '#f4f4f5',
    mutedForeground: '#71717a',
    primary: '#18181b',
    primaryForeground: '#ffffff',
    border: '#e4e4e7',
    accent: '#3b82f6',
    destructive: '#dc2626',
    success: '#16a34a',
    warning: '#d97706',
    info: '#0ea5e9',
  },
  typography: {
    body: { fontFamily: 'Helvetica', fontSize: 11, lineHeight: 1.6 },
    heading: {
      fontFamily: 'Times-Roman',
      fontWeight: 700,
      lineHeight: 1.25,
      fontSize: { h1: 32, h2: 24, h3: 20, h4: 16, h5: 14, h6: 12 },
    },
  },
  spacing: {
    page: { marginTop: 56, marginRight: 48, marginBottom: 56, marginLeft: 48 },
    sectionGap: 28,
    paragraphGap: 10,
    componentGap: 14,
  },
  page: { size: 'A4', orientation: 'portrait' },
};`;

export const manualStep4Context = `// This file was generated by pdfx init. You own it — customize freely.
// Docs: https://pdfx.akashpise.dev/installation#theming
//
// Provides React context for runtime theme switching.
// Wrap any subtree in <PdfxThemeProvider theme={myTheme}> to override the active theme.

/* eslint-disable react-refresh/only-export-components */
// This file intentionally exports both a component (PdfxThemeProvider) and hooks/context.
// All PDF components import from a single file — splitting would break the public API.

import { type DependencyList, type ReactNode, createContext, useContext, useMemo } from 'react';
import { theme as defaultTheme } from './pdfx-theme';

type PdfxTheme = typeof defaultTheme;

export const PdfxThemeContext = createContext<PdfxTheme>(defaultTheme);

export interface PdfxThemeProviderProps {
  theme?: PdfxTheme;
  children: ReactNode;
}

export function PdfxThemeProvider({ theme, children }: PdfxThemeProviderProps) {
  const resolvedTheme = useMemo(() => theme ?? defaultTheme, [theme]);
  return <PdfxThemeContext.Provider value={resolvedTheme}>{children}</PdfxThemeContext.Provider>;
}

/**
 * Returns the active PdfxTheme from context, or the default theme when called
 * outside a React render tree (e.g. unit tests).
 *
 * The try/catch is intentional: when components are invoked as plain functions
 * in unit tests, React's dispatcher is unavailable and useContext throws an
 * "Invalid hook call" error. We catch only that specific case and fall back to
 * defaultTheme. Any other error is re-thrown so real bugs are never swallowed.
 *
 * The eslint-disable is required because react-hooks/rules-of-hooks flags hooks
 * inside try/catch — this is the accepted pattern for libraries that must support
 * both React render and plain-function (test) invocation contexts.
 */
export function usePdfxTheme(): PdfxTheme {
  try {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    return useContext(PdfxThemeContext);
  } catch (error) {
    // Only suppress React dispatcher errors ("Invalid hook call").
    // Re-throw anything else so unexpected bugs surface clearly.
    if (
      error instanceof Error &&
      /invalid hook call|useContext|cannot read properties of null/i.test(error.message)
    ) {
      return defaultTheme;
    }
    throw error;
  }
}

/**
 * Memoises the result of factory(). Falls back to factory() directly when
 * called outside React (e.g. unit tests that invoke components as plain functions).
 *
 * Follows the same catch-narrowing strategy as usePdfxTheme.
 */
export function useSafeMemo<T>(factory: () => T, deps: DependencyList): T {
  try {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    return useMemo(factory, deps);
  } catch (error) {
    if (
      error instanceof Error &&
      /invalid hook call|useMemo|cannot read properties of null/i.test(error.message)
    ) {
      return factory();
    }
    throw error;
  }
}`;

export const manualStep5Structure = `your-project/
  src/
    lib/
      pdfx-theme.ts              # Theme tokens (Step 3)
      pdfx-theme-context.tsx     # Context, PdfxThemeProvider, usePdfxTheme (Step 4)
    components/
      pdfx/                      # ← All PDF components live here (isolated from UI components)
        heading/                 # Each component lives in its own subdirectory
          pdfx-heading.tsx       # Component
          pdfx-heading.styles.ts # Styles (customize freely)
          pdfx-heading.types.ts  # Types
        text/
          pdfx-text.tsx
          pdfx-text.styles.ts
          pdfx-text.types.ts
        badge/
          pdfx-badge.tsx
          pdfx-badge.styles.ts
          pdfx-badge.types.ts
        ...                      # One subdirectory per component
  pdfx.json                      # Project config (Step 2)`;

export const manualStep6AddComponent = `# Now you can copy components from each component's Manual tab.
# Or use the CLI to add them:
npx pdfx-cli add heading text table`;

export const themeProviderUsage = `import { PdfxThemeProvider } from '@pdfx/components';
import { modernTheme, minimalTheme } from '@pdfx/shared';

// Renders the entire document with the Modern theme
<PdfxThemeProvider theme={modernTheme}>
  <MyDocument />
</PdfxThemeProvider>

// Mix themes in the same document — components always read from the nearest provider
<Document>
  <Page>
    <PageHeader title="Report" />           {/* uses defaultTheme */}

    <PdfxThemeProvider theme={minimalTheme}>
      <DataTable columns={cols} data={rows} />  {/* uses minimalTheme */}
    </PdfxThemeProvider>
  </Page>
</Document>`;
