import type { PdfxTheme } from '@pdfx/shared';

/**
 * Generates a standalone TypeScript theme file from a PdfxTheme preset.
 *
 * The output inlines the PdfxTheme type so consuming projects do not need
 * to import theme types from @pdfx/shared.
 */
export function generateThemeFile(preset: PdfxTheme): string {
  return `// Generated by pdfx init.
// See: https://pdfx.akashpise.dev/installation#theming
//
// This module is the single source of truth for PDFX styling tokens.
// Update the exported \`theme\` object to customize component styles.

// Theme type

interface PdfxTheme {
  name: string;
  primitives: {
    typography: Record<string, number>;
    spacing: Record<string | number, number>;
    fontWeights: { regular: number; medium: number; semibold: number; bold: number };
    lineHeights: { tight: number; normal: number; relaxed: number };
    borderRadius: { none: number; sm: number; md: number; lg: number; full: number };
    letterSpacing: { tight: number; normal: number; wide: number; wider: number };
  };
  colors: {
    foreground: string;
    background: string;
    muted: string;
    mutedForeground: string;
    primary: string;
    primaryForeground: string;
    border: string;
    accent: string;
    destructive: string;
    success: string;
    warning: string;
    info: string;
  };
  typography: {
    body: { fontFamily: string; fontSize: number; lineHeight: number };
    heading: {
      fontFamily: string;
      fontWeight: number;
      lineHeight: number;
      fontSize: { h1: number; h2: number; h3: number; h4: number; h5: number; h6: number };
    };
  };
  spacing: {
    page: { marginTop: number; marginRight: number; marginBottom: number; marginLeft: number };
    sectionGap: number;
    paragraphGap: number;
    componentGap: number;
  };
  page: {
    size: 'A4' | 'LETTER' | 'LEGAL';
    orientation: 'portrait' | 'landscape';
  };
}

// Theme values

export const theme: PdfxTheme = ${serializeTheme(preset)};
`;
}

/** Serializes a PdfxTheme to formatted TypeScript source code */
function serializeTheme(t: PdfxTheme): string {
  return `{
  name: '${t.name}',

  // Primitive scales.
  primitives: {
    typography: {
      xs: ${t.primitives.typography.xs},
      sm: ${t.primitives.typography.sm},
      base: ${t.primitives.typography.base},
      lg: ${t.primitives.typography.lg},
      xl: ${t.primitives.typography.xl},
      '2xl': ${t.primitives.typography['2xl']},
      '3xl': ${t.primitives.typography['3xl']},
    },
    spacing: {
      0: ${t.primitives.spacing[0]},
      0.5: ${t.primitives.spacing[0.5]},
      1: ${t.primitives.spacing[1]},
      2: ${t.primitives.spacing[2]},
      3: ${t.primitives.spacing[3]},
      4: ${t.primitives.spacing[4]},
      5: ${t.primitives.spacing[5]},
      6: ${t.primitives.spacing[6]},
      8: ${t.primitives.spacing[8]},
      10: ${t.primitives.spacing[10]},
      12: ${t.primitives.spacing[12]},
      16: ${t.primitives.spacing[16]},
    },
    fontWeights: {
      regular: ${t.primitives.fontWeights.regular},
      medium: ${t.primitives.fontWeights.medium},
      semibold: ${t.primitives.fontWeights.semibold},
      bold: ${t.primitives.fontWeights.bold},
    },
    lineHeights: {
      tight: ${t.primitives.lineHeights.tight},
      normal: ${t.primitives.lineHeights.normal},
      relaxed: ${t.primitives.lineHeights.relaxed},
    },
    borderRadius: {
      none: ${t.primitives.borderRadius.none},
      sm: ${t.primitives.borderRadius.sm},
      md: ${t.primitives.borderRadius.md},
      lg: ${t.primitives.borderRadius.lg},
      full: ${t.primitives.borderRadius.full},
    },
    letterSpacing: {
      tight: ${t.primitives.letterSpacing.tight},
      normal: ${t.primitives.letterSpacing.normal},
      wide: ${t.primitives.letterSpacing.wide},
      wider: ${t.primitives.letterSpacing.wider},
    },
  },

  // Semantic colors. Values must be valid for react-pdf.
  colors: {
    foreground: '${t.colors.foreground}',
    background: '${t.colors.background}',
    muted: '${t.colors.muted}',
    mutedForeground: '${t.colors.mutedForeground}',
    primary: '${t.colors.primary}',
    primaryForeground: '${t.colors.primaryForeground}',
    border: '${t.colors.border}',
    accent: '${t.colors.accent}',
    destructive: '${t.colors.destructive}',
    success: '${t.colors.success}',
    warning: '${t.colors.warning}',
    info: '${t.colors.info}',
  },

  // Typography defaults.
  typography: {
    body: {
      fontFamily: '${t.typography.body.fontFamily}',
      fontSize: ${t.typography.body.fontSize},
      lineHeight: ${t.typography.body.lineHeight},
    },
    heading: {
      fontFamily: '${t.typography.heading.fontFamily}',
      fontWeight: ${t.typography.heading.fontWeight},
      lineHeight: ${t.typography.heading.lineHeight},
      fontSize: {
        h1: ${t.typography.heading.fontSize.h1},
        h2: ${t.typography.heading.fontSize.h2},
        h3: ${t.typography.heading.fontSize.h3},
        h4: ${t.typography.heading.fontSize.h4},
        h5: ${t.typography.heading.fontSize.h5},
        h6: ${t.typography.heading.fontSize.h6},
      },
    },
  },

  // Layout spacing.
  spacing: {
    page: {
      marginTop: ${t.spacing.page.marginTop},
      marginRight: ${t.spacing.page.marginRight},
      marginBottom: ${t.spacing.page.marginBottom},
      marginLeft: ${t.spacing.page.marginLeft},
    },
    sectionGap: ${t.spacing.sectionGap},
    paragraphGap: ${t.spacing.paragraphGap},
    componentGap: ${t.spacing.componentGap},
  },

  // Page defaults.
  page: {
    size: '${t.page.size}',
    orientation: '${t.page.orientation}',
  },
}`;
}

/**
 * Generates a standalone pdfx-theme-context.tsx file.
 *
 * The generated module exports PdfxThemeContext, PdfxThemeProvider,
 * usePdfxTheme, and useSafeMemo for runtime theme overrides.
 */
export function generateThemeContextFile(): string {
  return `// Generated by pdfx init.
// See: https://pdfx.akashpise.dev/installation#theming
//
// Provides runtime theme overrides via React context.
// Wrap a subtree in <PdfxThemeProvider theme={myTheme}> to override defaults.

/* eslint-disable react-refresh/only-export-components */
// Intentional: this module exports both a component and hooks/context.
// Keeping a single import surface preserves the generated public API.

import { type DependencyList, type ReactNode, createContext, useContext } from 'react';
import { theme as defaultTheme } from './pdfx-theme';

type PdfxTheme = typeof defaultTheme;

export const PdfxThemeContext = createContext<PdfxTheme>(defaultTheme);

export interface PdfxThemeProviderProps {
  theme?: PdfxTheme;
  children: ReactNode;
}

export function PdfxThemeProvider({ theme, children }: PdfxThemeProviderProps) {
  const resolvedTheme = theme ?? defaultTheme;
  return <PdfxThemeContext.Provider value={resolvedTheme}>{children}</PdfxThemeContext.Provider>;
}

/**
 * Returns the active theme from context.
 *
 * When called outside a React render tree (for example in plain-function tests),
 * React may throw an invalid hook error. In that case we return defaultTheme.
 * Unexpected errors are re-thrown.
 */
export function usePdfxTheme(): PdfxTheme {
  try {
    return useContext(PdfxThemeContext);
  } catch (error) {
    // Suppress only known React dispatcher errors.
    if (
      error instanceof Error &&
      /invalid hook call|useContext|cannot read properties of null/i.test(error.message)
    ) {
      return defaultTheme;
    }
    throw error;
  }
}

/**
 * Calls factory() and returns the result.
 * The deps parameter is accepted for API compatibility with existing callers.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function useSafeMemo<T>(factory: () => T, _deps: DependencyList): T {
  return factory();
}
`;
}
